apiVersion: v1
entries:
  typo3:
  - annotations:
      artifacthub.io/changes: |
        - kind: changed
          description: added support for stable autoscaling api
      artifacthub.io/screenshots: |
        - title: TYPO3 is a very powerful Web Content Management System.
          url: https://docs.typo3.org/m/typo3/tutorial-getting-started/10.4/en-us/_images/BackendAboutModules.png
        - title: Easilly create and manage pages for your website.
          url: https://typo3.org/fileadmin/t3o_common_storage/images/release_notes/v12/12.0/screenshots/backend-ux-page-tree.png
        - title: Manage existing and add new content to your pages.
          url: https://typo3.org/fileadmin/t3o_common_storage/images/release_notes/v12/12.0/screenshots/new-page-module.png
        - title: Files including documents and images can be managed in the Filelist module.
          url: https://docs.typo3.org/m/typo3/tutorial-editors/main/en-us/_images/FilelistModule.png
        - title: Extensions can be installed and managed from the Extension Manager.
          url: https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/_images/ExtensionManager76To86.png
        - title: Create your own dashboard to visualize information inside of your TYPO3 backend.
          url: https://typo3.org/fileadmin/t3o_common_storage/images/release_notes/v10/10.4/typo3-100400_0036_dashboard-my-dashboard.png
      artifacthub.io/signKey: |
        fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
        url: https://charts.christianhuth.de/public.key
    apiVersion: v2
    appVersion: "12.4"
    created: "2024-11-28T14:14:40.474138+01:00"
    dependencies:
    - condition: mysql.enabled
      name: mysql
      repository: https://charts.bitnami.com/bitnami
      version: 9.23.0
    - condition: mariadb.enabled
      name: mariadb
      repository: https://charts.bitnami.com/bitnami
      version: 16.5.0
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 14.3.3
    description: TYPO3 — the Professional, Flexible Content Management System
    digest: db20a509055e24d0be2a8c8cdcc1d220e61354b0541c84d8946533fe38fbc6c7
    home: https://github.com/christianhuth/helm-charts
    icon: https://www.mdc.de/wp-content/uploads/2016/05/typo3_logo.png
    maintainers:
    - email: christian@knell.it
      name: christianhuth
    name: typo3
    sources:
    - https://github.com/martin-helmich/docker-typo3
    - https://github.com/TYPO3/typo3
    type: application
    urls:
    - https://wegerhoff.github.io/helm-charts/charts/typo3/typo3-2.3.3.tgz
    version: 2.3.3
generated: "2024-11-28T14:14:40.465379+01:00"
