apiVersion: v2
name: kutt
description: Kutt is a free modern URL shortener.
type: application
version: 4.2.2
appVersion: "v2.7.4"
home: https://github.com/christianhuth/helm-charts
icon: https://www.saashub.com/images/app/service_logos/15/d634f2359578/large.png
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/thedevs-network/kutt
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 14.3.3
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.19.4
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: URL of Helm Repository in README
  artifacthub.io/screenshots: |
    - title: Simply shorten your link using the Web UI.
      url: https://d4.alternativeto.net/v9sHosD3RiPblfBOOHZi0gwU1M0pRL6Jn53oiobJi9k/rs:fit:1200:1200:0/g:ce:0:0/YWJzOi8vZGlzdC9zL2t1dHQtaXRfNzY3MjMzX2Z1bGwucG5n.jpg
    - title: You can see a list of the most recent created links and some statistical data about them.
      url: https://docs.cloudron.io/img/kutt-admin.png
    - title: View detailed statistics about each created link.
      url: https://kutt.it/images/callout.png
    - title: Kutt supports having more than one domain.
      url: https://docs.cloudron.io/img/kutt-custom-domain.png
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
